version: "3"
services:
  app:
    image: luisalejandro/agoras-actions:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/agoras/app
      - ../agoras:/home/agoras/agoras-src:ro
      - ~/Library/Caches/pip:/home/agoras/.cache/pip
