[tox]
envlist = lint, format, coverage

[testenv:lint]
skip_install = True
deps =
    ruff
    pydocstyle
    bandit
    pyright
commands =
    ruff format --check docker
    ruff check docker
    pydocstyle docker
    bandit -c pyproject.toml -r docker
    pyright docker

[testenv:format]
skip_install = True
deps =
    ruff
commands =
    ruff format docker
    ruff check --fix --select F401,F841,I001 docker

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}/docker
deps =
    coverage
    agoras==2.0.5
commands =
    coverage run --source execute -m unittest discover -s docker -p 'test_*.py' -v
    coverage report -m
