[tox]
envlist = lint, format, coverage

[flake8]
max-line-length = 120
max-complexity = 12

[testenv:lint]
skip_install = True
deps =
    flake8
commands =
    flake8 docker

[testenv:format]
skip_install = True
deps =
    autopep8
commands =
    autopep8 --diff --recursive --aggressive --aggressive docker

[testenv:coverage]
skip_install = True
setenv =
    PYTHONPATH = {toxinidir}/docker
deps =
    coverage
    agoras==2.0.4
commands =
    coverage run --source execute -m unittest discover -s docker -p 'test_*.py' -v
    coverage report -m
